// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AnalysisDefinitionDto = { definition_id: string, kind: string, name: string, description: string | null, dataset_ids: Array<string>, query_text: string, algorithm_id: string, algorithm_version: number, field_selection_json: string, config_json: string, masking_profile_json: string, limits_json: string, created_at: string, updated_at: string, revision: number, };
