// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BundleImportSummaryDto = { investigation_id: string, evidence: number, hypotheses: number, items: number, markers: number, saved_searches: number, reports: number, data_included: boolean, 
/**
 * Where the new isolated workspace was created.
 */
workspace_root: string, };
