// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BundleExportDto = { bundle_id: string, investigation_id: string, destination_path: string, checksum_sha256: string | null, byte_size: number | null, 
/**
 * `running | completed | failed | cancelled`.
 */
status: string, 
/**
 * `full_within_declared_dataset_revision | included_subset_only | snapshot_only`.
 */
reproduction_scope: string | null, created_at: string, finished_at: string | null, };
