// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One behavioural signal (`sig-rules` v1).
 */
export type CorrelationSignalDto = { signal_id: string, group_id: string, 
/**
 * `retry | operational_duplicate | clock_skew | gap`.
 */
kind: string, rule_id: string, rule_version: number, 
/**
 * `documented | corroborated | indicative`.
 */
strength: string, 
/**
 * True for everything the source did not state itself. A column so
 * the UI can label leads without parsing prose.
 */
investigative_lead: boolean, from_record_id: string, to_record_id: string, from_event_time: bigint, to_event_time: bigint, delta_nanos: bigint, tolerance_nanos: bigint | null, 
/**
 * JSON arrays of typed field names.
 */
matched_json: string, missing_json: string, reason: string, };
