// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One correlation group.
 */
export type CorrelationGroupDto = { group_id: string, key_selector: string, key_value: string, 
/**
 * `exact | correlated | probable`.
 */
confidence: string, event_count: number, 
/**
 * Members carrying the key but with no event time: counted, never
 * ordered.
 */
undated_count: number, truncated_count: number, 
/**
 * Nanosecond timestamps exceed JS exact-integer range, so these
 * stay bigint and the UI converts through BigInt.
 */
first_event_time: bigint | null, last_event_time: bigint | null, resources_json: string, edge_count: number, rule_id: string, rule_version: number, reason: string, };
