// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Structured error envelope for every command (stable codes).
 */
export type ErrorDto = { code: string, message: string, };
