// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EvidenceGroupDto = { group_id: string, investigation_id: string, name: string, position: bigint, revision: bigint, };
