// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FacetValueDto } from "./FacetValueDto";

export type FacetDto = { display: string, values: Array<FacetValueDto>, missing_count: bigint, truncated: boolean, 
/**
 * Set when the field could not be faceted (unknown/conflicting type).
 */
error: string | null, };
