// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FacetValueDto } from "./FacetValueDto";

export type FieldSummaryDto = { display: string, present_count: bigint, missing_count: bigint, distinct_count: bigint, distinct_is_exact: boolean, top_values: Array<FacetValueDto>, min_numeric: number | null, max_numeric: number | null, high_cardinality: boolean, types: Array<string>, };
