// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FieldInfoDto } from "./FieldInfoDto";

export type FieldCatalogDto = { fields: Array<FieldInfoDto>, complete: boolean, fts_ready: boolean, };
