// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FieldInfoDto = { display: string, 
/**
 * `canonical` or `attribute`.
 */
origin: string, types: Array<string>, present_count: bigint, distinct_est: bigint, distinct_is_exact: boolean, examples: Array<string>, queryable: boolean, facetable: boolean, };
