// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HistogramBinDto } from "./HistogramBinDto";

export type HistogramDto = { request_id: string, bins: Array<HistogramBinDto>, bin_width_nanos: bigint, start: bigint, end: bigint, total_in_range: bigint, untimestamped_count: bigint, empty: boolean, 
/**
 * Display timezone of the axis (always UTC in v0.2).
 */
timezone: string, };
