// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Full editable-field update (status changes use their own command so
 * the transition is auditable as such).
 */
export type InvestigationEditDto = { investigation_id: string, expected_revision: bigint, title: string, description: string | null, severity: string | null, owner_text: string | null, tags: Array<string>, incident_started_at: bigint | null, mitigated_at: bigint | null, resolved_at: bigint | null, window_start: bigint | null, window_end: bigint | null, };
