// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type JobDto = { job_id: string, kind: string, status: string, dataset_id: string | null, created_at: string, updated_at: string, error_json: string | null, };
