// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LogRowDto } from "./LogRowDto";

export type LogPageDto = { rows: Array<LogRowDto>, has_more: boolean, limit: number, };
