// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MarkerEditDto = { marker_id: string, expected_revision: number, kind: string, label: string, description: string | null, time_text: string | null, end_time_text: string | null, };
