// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MarkerDto = { marker_id: string, investigation_id: string, 
/**
 * `deployment | config_change | operator_action | custom`.
 */
kind: string, label: string, description: string | null, at_nanos: number | null, end_nanos: number | null, original_tz_offset_min: number | null, 
/**
 * Timestamp text exactly as the user entered it.
 */
original_time_text: string | null, position: number, archived: boolean, created_at: string, updated_at: string, revision: number, };
