// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Typed correlation definition. The key selector and its normalization
 * are one decision, so they cross the boundary together and are parsed
 * immediately — a refusal must happen before a definition exists.
 */
export type NewCorrelationDefinitionDto = { name: string, description: string | null, dataset_ids: Array<string>, query_text: string, 
/**
 * `trace_id | trace_span | request_id | transaction_id |
 * message_id | entity_id | attribute`. There is deliberately no
 * `span_id`: a span ID is unique only within its trace.
 */
key: string, 
/**
 * Required when `key` is `attribute`.
 */
attribute: string | null, trim: boolean, case_fold: boolean, strip_prefix: string | null, 
/**
 * Signals to evaluate. An empty list means none, which is a
 * different request from omitting the field and is honoured as
 * written.
 */
signals: Array<string>, 
/**
 * Attribute holding an explicit attempt counter. Without it a
 * retry can never be reported as documented.
 */
attempt_attribute: string | null, clock_skew_tolerance_nanos: number, gap_threshold_nanos: number, };
