// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NewInvestigationDto = { title: string, description: string | null, severity: string | null, owner_text: string | null, tags: Array<string>, incident_started_at: bigint | null, window_start: bigint | null, window_end: bigint | null, };
