// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Marker creation input. Times arrive as RFC 3339 text and are parsed
 * Rust-side; the original text and zone offset are preserved verbatim.
 * No time = the undated section.
 */
export type NewMarkerDto = { investigation_id: string, kind: string, label: string, description: string | null, time_text: string | null, 
/**
 * Optional interval end (exclusive); requires `time_text`.
 */
end_time_text: string | null, };
