// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PatternSummaryDto = { pattern_id: string, kind: string, template: string, exception_type: string | null, count: number, untimestamped: number, first_seen: number | null, last_seen: number | null, peak_bucket_start: number | null, peak_bucket_count: number, buckets_truncated: boolean, services_truncated: boolean, parse_quality: string | null, services_json: string, examples_json: string, };
