// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PinCommonDto = { investigation_id: string, title: string, annotation: string | null, relevance: string | null, group_id: string | null, };
