// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PinCommonDto } from "./PinCommonDto";

export type PinItemDto = { common: PinCommonDto, item_id: string, };
