// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PinCommonDto } from "./PinCommonDto";
import type { QueryScopeDto } from "./QueryScopeDto";

export type PinSelectionDto = { common: PinCommonDto, record_ids: Array<string>, scope: QueryScopeDto, };
