// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One record admitted to a probable neighborhood.
 */
export type ProbableNeighborDto = { record_id: string, event_time: bigint, delta_nanos: bigint, matched_fields: Array<string>, 
/**
 * `observed | inferred | missing`.
 */
time_quality: string, };
