// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TimeStrategyDto } from "./TimeStrategyDto";

/**
 * The exact Explorer scope a pin is made from.
 */
export type QueryScopeDto = { query_text: string, dataset_ids: Array<string>, time_strategy: TimeStrategyDto, };
