// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LogRowV2Dto } from "./LogRowV2Dto";

export type RecordDetailDto = { row: LogRowV2Dto, body_json: string | null, event_name: string | null, resource_json: string | null, scope_json: string | null, provenance_json: string, timestamp_quality: Array<string>, original_timestamp_text: string | null, profile_id: string | null, profile_version: string | null, parser_id: string | null, parser_version: string | null, normalizer_version: string | null, };
