// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ResolvedWindowDto = { start: bigint | null, end: bigint | null, start_text: string | null, end_text: string | null, empty_anchor: boolean, };
