// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TimeStrategyDto } from "./TimeStrategyDto";

export type RunQueryDto = { 
/**
 * Client-generated identity used for cancellation and stale-response
 * protection.
 */
request_id: string, dataset_ids: Array<string>, query_text: string, time_strategy: TimeStrategyDto, cursor: string | null, backward: boolean, limit: number, 
/**
 * Also record this run in recent searches (first page only).
 */
record_recent: boolean, };
