// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TimeStrategyDto } from "./TimeStrategyDto";

export type SavedSearchDto = { saved_search_id: string, name: string, query_text: string, language_version: bigint, fingerprint: string, dataset_ids: Array<string>, 
/**
 * Empty vec + `all_datasets == true` = all compatible datasets.
 */
all_datasets: boolean, time_strategy: TimeStrategyDto, created_at: string, updated_at: string, };
