// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LogRowV2Dto } from "./LogRowV2Dto";

export type SourceContextDto = { records: Array<LogRowV2Dto>, anchor_record_id: string, 
/**
 * available | changed | missing | unsupported.
 */
source_status: string, source_path: string | null, 
/**
 * Bounded raw bytes of the anchor record from the original file, when
 * available and unchanged (lossless view of multiline framing).
 */
raw_excerpt: string | null, range_low: bigint, range_high: bigint, };
