// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TimelineEntryDto = { 
/**
 * `marker` or `evidence`.
 */
entry_kind: string, id: string, detail_kind: string, title: string, at_nanos: number | null, end_nanos: number | null, 
/**
 * `marker | event_time | interval_bounds | resolved_window | none`.
 */
time_source: string, undated_reason: string | null, description: string | null, original_time_text: string | null, original_tz_offset_min: number | null, };
