// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Persistable time strategy (`kind`: all | absolute | relative_to_latest).
 */
export type TimeStrategyDto = { kind: string, start: bigint | null, end: bigint | null, duration_nanos: bigint | null, };
