// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EvidenceOutcomeDto } from "./EvidenceOutcomeDto";

export type VerificationReportDto = { total: bigint, updated: bigint, cancelled: boolean, dataset_lookups: bigint, 
/**
 * State name → count.
 */
states: { [key in string]: bigint }, outcomes: Array<EvidenceOutcomeDto>, duration_ms: bigint, };
