// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AnalysisRunDto = { run_id: string, definition_id: string, definition_revision: number, semantic_fingerprint: string, state: string, dataset_revs_json: string, bounds_json: string, counts_json: string, warnings_json: string, manifest_json: string | null, error_json: string | null, invalidation_reason: string | null, started_at: string, finished_at: string | null, };
