// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnalysisRunDto } from "./AnalysisRunDto";
import type { ErrorDto } from "./ErrorDto";

/**
 * Terminal event for a pattern-analysis job (`analysis-finished`).
 */
export type AnalysisFinishedDto = { job_id: string, definition_id: string, run: AnalysisRunDto | null, error: ErrorDto | null, };
