// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One classified comparison row. `rate_change_bp` is basis points as a
 * decimal string or `"undefined"` (zero baseline) — never a float and
 * never an infinity, so the UI displays what was computed.
 */
export type ComparisonResultDto = { result_id: string, dimension: string, key: string, classification: string, baseline_count: number, suspect_count: number, count_change: number, rate_change_bp: string, rule_id: string, rule_version: number, calculation_json: string, };
