// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One edge between consecutive records of a group.
 */
export type CorrelationEdgeDto = { edge_id: string, group_id: string, from_record_id: string, to_record_id: string, from_event_time: bigint, to_event_time: bigint, 
/**
 * Reported as measured. A negative value is a real observation
 * about the data, not an error to correct.
 */
delta_nanos: bigint, confidence: string, reason: string, };
