// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DatasetDto = { dataset_id: string, name: string, signal: string, status: string, created_at: string, row_count: bigint, byte_size: bigint, segment_count: bigint, };
