// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpanDto } from "./SpanDto";

export type DiagnosticDto = { code: string, 
/**
 * `error` or `warning`.
 */
severity: string, message: string, span: SpanDto, expected: string | null, hint: string | null, };
