// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EvidenceDto = { evidence_id: string, investigation_id: string, kind: string, signal: string, title: string, annotation: string | null, relevance: string | null, group_id: string | null, position: bigint, supersedes_evidence_id: string | null, archived: boolean, 
/**
 * Latest resolver integrity state (`unverified` until first verify).
 */
resolver_state: string, 
/**
 * Structured detail for the state, exactly as the resolver wrote it.
 */
resolver_detail_json: string, last_verified_at: string | null, 
/**
 * Versioned envelope payloads; the UI renders snapshots read-only
 * and never re-interprets references (jump-back goes through
 * `evidence_restore_context`).
 */
envelope_version: bigint, snapshot_json: string, created_at: string, updated_at: string, revision: bigint, };
