// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrorDto } from "./ErrorDto";

export type ExportStatusDto = { export_id: string, job_id: string, status: string, rows_written: bigint, bytes_written: bigint, truncated: boolean, destination: string, error: ErrorDto | null, };
