// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TimeStrategyDto } from "./TimeStrategyDto";

export type FieldSummaryRequestDto = { request_id: string, dataset_ids: Array<string>, query_text: string, time_strategy: TimeStrategyDto, field: string, };
