// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpanDto } from "./SpanDto";

export type HighlightDto = { 
/**
 * field | term | keyword | string | regex | operator | paren.
 */
kind: string, span: SpanDto, };
