// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HistoryDto = { history_id: bigint, entity_kind: string, entity_id: string, revision: bigint, action: string, detail_json: string, created_at: string, };
