// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HypothesisDto = { hypothesis_id: string, investigation_id: string, statement: string, rationale: string | null, state: string, position: bigint, created_at: string, updated_at: string, revision: bigint, 
/**
 * Evidence linked to this hypothesis (ids into the bundle's list).
 */
linked_evidence_ids: Array<string>, };
