// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type IndexStateDto = { kind: string, dataset_id: string, version: bigint, status: string, };
