// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EvidenceDto } from "./EvidenceDto";
import type { EvidenceGroupDto } from "./EvidenceGroupDto";
import type { HypothesisDto } from "./HypothesisDto";
import type { InvestigationDto } from "./InvestigationDto";
import type { ItemDto } from "./ItemDto";

/**
 * Everything the investigation workspace view needs in one fetch.
 */
export type InvestigationBundleDto = { investigation: InvestigationDto, hypotheses: Array<HypothesisDto>, items: Array<ItemDto>, evidence: Array<EvidenceDto>, groups: Array<EvidenceGroupDto>, };
