// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ItemDto = { item_id: string, investigation_id: string, kind: string, content: string, task_status: string | null, question_status: string | null, authored_by_user: boolean, position: number, archived: boolean, created_at: string, updated_at: string, revision: number, };
