// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LogQueryDto = { dataset_ids: Array<string>, time_start: bigint | null, time_end: bigint | null, min_severity: number | null, contains_text: string | null, limit: number, offset: number, };
