// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LogRowDto = { record_id: string, event_time: bigint | null, event_time_text: string | null, severity_text: string | null, severity_number: number | null, display_message: string, dataset_id: string, record_number: bigint | null, line_start: bigint | null, attributes_json: string, };
