// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LogRowV2Dto = { record_id: string, event_time: bigint | null, event_time_text: string | null, severity: string | null, severity_text: string | null, severity_number: number | null, message: string, trace_id: string | null, span_id: string | null, dataset_id: string, source_id: string, record_number: bigint | null, line_start: bigint | null, attributes_json: string, };
