// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Creation payload for a window comparison. Both windows are explicit
 * concrete UTC nanos: a preset must resolve to visible bounds in the
 * UI before it reaches this boundary, never after.
 */
export type NewComparisonDefinitionDto = { name: string, description: string | null, dataset_ids: Array<string>, query_text: string, 
/**
 * `message_pattern | stack_fingerprint | severity | resource |
 * operation | outcome | event_name | attribute`.
 */
dimension: string, 
/**
 * Required when `dimension` is `attribute`.
 */
attribute: string | null, 
/**
 * Required when `dimension` is `stack_fingerprint`.
 */
stack_field: string | null, baseline_start: bigint, baseline_end: bigint, suspect_start: bigint, suspect_end: bigint, top_k: number | null, thresholds_json: string, masking_profile_json: string, };
