// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NewItemDto = { investigation_id: string, 
/**
 * `note` | `task` | `finding` | `question`.
 */
kind: string, content: string, task_status: string | null, question_status: string | null, };
