// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Creation payload for the two pattern-analysis kinds. `stack_field`
 * is required when `kind` is `stack_fingerprint`.
 */
export type NewPatternDefinitionDto = { kind: string, name: string, description: string | null, dataset_ids: Array<string>, query_text: string, stack_field: string | null, masking_profile_json: string, config_json: string, limits_json: string, };
