// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DatasetDto } from "./DatasetDto";
import type { JobDto } from "./JobDto";
import type { WorkspaceInfoDto } from "./WorkspaceInfoDto";

export type OverviewDto = { workspace: WorkspaceInfoDto, datasets: Array<DatasetDto>, jobs: Array<JobDto>, };
