// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PinCommonDto } from "./PinCommonDto";

export type PinEventDto = { common: PinCommonDto, dataset_id: string, record_id: string, display_fields: Array<string>, include_raw_excerpt: boolean, };
