// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PinCommonDto } from "./PinCommonDto";
import type { QueryScopeDto } from "./QueryScopeDto";

export type PinGroupDto = { common: PinCommonDto, scope: QueryScopeDto, field: string, 
/**
 * JSON-encoded scalar; `null` selects the missing-value group.
 */
value_json: string, };
