// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PinCommonDto } from "./PinCommonDto";
import type { QueryScopeDto } from "./QueryScopeDto";

export type PinIntervalDto = { common: PinCommonDto, scope: QueryScopeDto, start: bigint, end: bigint, bucket_width_nanos: bigint, display_timezone: string, 
/**
 * Visible neighbor buckets as (bucket_start, count) pairs.
 */
neighbor_buckets: Array<[bigint, bigint]>, };
