// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProbableNeighborDto } from "./ProbableNeighborDto";

/**
 * A neighborhood anchored to one selected record. Every term gate 21
 * requires is a field here rather than something the UI assembles.
 */
export type ProbableNeighborhoodDto = { anchor_record_id: string, anchor_event_time: bigint, anchor_time_quality: string, rule_id: string, rule_version: number, 
/**
 * Always `probable`.
 */
confidence: string, compatible_fields: Array<string>, constraints: string, tolerance_nanos: bigint, neighbors: Array<ProbableNeighborDto>, admitted: number, truncated: number, scanned: number, reason: string, };
