// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiagnosticDto } from "./DiagnosticDto";
import type { HighlightDto } from "./HighlightDto";

export type QueryAnalysisDto = { valid: boolean, diagnostics: Array<DiagnosticDto>, highlights: Array<HighlightDto>, fingerprint: string | null, language_version: number, 
/**
 * Catalog completeness for the selection (suggestions may be partial
 * while a catalog build is pending).
 */
catalog_complete: boolean, };
