// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiagnosticDto } from "./DiagnosticDto";
import type { LogRowV2Dto } from "./LogRowV2Dto";
import type { ResolvedWindowDto } from "./ResolvedWindowDto";

export type QueryPageV2Dto = { request_id: string, rows: Array<LogRowV2Dto>, next_cursor: string | null, prev_cursor: string | null, has_more: boolean, matching: bigint, omitted_untimestamped: bigint, resolved_window: ResolvedWindowDto, elapsed_ms: bigint, used_fts: boolean, used_fallback_text_scan: boolean, warnings: Array<DiagnosticDto>, };
