// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TimeStrategyDto } from "./TimeStrategyDto";

export type RecentSearchDto = { recent_id: bigint, query_text: string, language_version: bigint, dataset_ids: Array<string>, all_datasets: boolean, time_strategy: TimeStrategyDto, run_count: bigint, last_run_at: string, };
