// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RecoveryDto = { discarded_staging_dirs: Array<string>, removed_orphan_files: Array<string>, interrupted_jobs: Array<string>, discarded_staging_datasets: Array<string>, 
/**
 * `running` report/bundle records finished as failed on reopen.
 */
interrupted_case_records: Array<string>, };
