// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Disclosure profile. `rules_json`/`posture_json` are the stored
 * documents; they are validated by compiling the projection at every
 * save and load, never trusted as-is.
 */
export type RedactionProfileDto = { profile_id: string, name: string, 
/**
 * Bumps on every rule/posture change; artifacts name it.
 */
profile_version: number, rules_json: string, posture_json: string, created_at: string, updated_at: string, revision: number, };
