// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Immutable generation record.
 */
export type ReportArtifactDto = { artifact_id: string, report_def_id: string, 
/**
 * `markdown` or `html`.
 */
format: string, destination_path: string, checksum_sha256: string | null, byte_size: number | null, 
/**
 * `running | completed | failed | cancelled`.
 */
status: string, error_json: string | null, created_at: string, finished_at: string | null, };
