// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TimeStrategyDto } from "./TimeStrategyDto";

/**
 * Decoded restore instructions for one evidence item: exactly what was
 * captured, never broadened. `kind` mirrors the evidence kind; unused
 * fields stay `None` for kinds that do not carry them.
 */
export type RestoreContextDto = { kind: string, 
/**
 * Authoritative query text to restore (for group pins this is the
 * captured base query composed with the group predicate).
 */
query_text: string | null, dataset_ids: Array<string>, time_strategy: TimeStrategyDto | null, 
/**
 * Concrete half-open bounds resolved at pin time.
 */
resolved_start: bigint | null, resolved_end: bigint | null, 
/**
 * Event pins: the record to focus.
 */
record_id: string | null, dataset_id: string | null, 
/**
 * Selection pins: the captured ids, in order.
 */
record_ids: Array<string>, 
/**
 * Interval pins: the exact half-open interval.
 */
interval_start: bigint | null, interval_end: bigint | null, 
/**
 * Item pins: the referenced workspace item.
 */
item_id: string | null, };
