// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One ordered report section. Narrative kinds carry user-authored
 * content (blank renders the explicit word `unknown`); projection kinds
 * (`timeline`/`hypotheses`/`evidence`) ignore `content`.
 */
export type SectionDto = { kind: string, content: string | null, };
