// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A selected child at the exact revision the author chose.
 */
export type SelectedRefDto = { id: string, revision: number, };
