// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SpanDto = { start: number, end: number, start_utf16: number, end_utf16: number, };
