// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TimeStrategyDto } from "./TimeStrategyDto";

export type StartExportDto = { dataset_ids: Array<string>, query_text: string, time_strategy: TimeStrategyDto, 
/**
 * csv | jsonl.
 */
format: string, destination: string, row_limit: bigint | null, byte_limit: bigint | null, csv_columns: Array<string>, };
