// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StartImportDto = { paths: Array<string>, dataset_name: string, 
/**
 * Built-in profile selector for the v0.0 proof UI: `jsonl` or `csv`.
 */
format: string, };
