// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TimelineEntryDto } from "./TimelineEntryDto";

export type TimelineDto = { dated: Array<TimelineEntryDto>, undated: Array<TimelineEntryDto>, archived_excluded: number, };
