// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrorDto } from "./ErrorDto";
import type { VerificationReportDto } from "./VerificationReportDto";

/**
 * Terminal payload of a verification job (emitted as `verify-finished`).
 */
export type VerifyFinishedDto = { job_id: string, investigation_id: string, report: VerificationReportDto | null, error: ErrorDto | null, };
