// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VerifyStartedDto = { job_id: string, 
/**
 * Number of evidence items the run will consider.
 */
total: bigint, };
