// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EvidenceOutcomeDto } from "./EvidenceOutcomeDto";

export type VerificationReportDto = { total: number, updated: number, cancelled: boolean, dataset_lookups: number, 
/**
 * State name → count.
 */
states: Record<string, number>, outcomes: Array<EvidenceOutcomeDto>, duration_ms: number, };
