// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RecoveryDto } from "./RecoveryDto";

export type WorkspaceInfoDto = { root: string, workspace_id: string, name: string, schema_version: bigint, product_version: string, available_signals: Array<string>, 
/**
 * Present when opening performed crash recovery.
 */
recovery: RecoveryDto | null, };
