//! W9 end-to-end workflow proof, entirely through the service layer:
//! import → investigate (hypothesis, item, marker) → pin → verify →
//! timeline → report (preview == generated bytes, deterministic) →
//! bundle export (deterministic) → re-import into a NEW workspace whose
//! verification stays honest about the missing canonical dataset.
//! One test drives the whole chain so every hand-off between services
//! is exercised on real state, not fixtures.

use std::io::Write as _;
use std::path::Path;

use logscope_app::case::{self, PinCommon, QueryScope};
use logscope_app::{bundle, explorer, report, run_import, timeline, ImportRequest};
use logscope_ingest::builtin;
use logscope_jobs::{JobContext, JobControl};
use logscope_query::{query_page, EngineConnection, PageRequest, QueryCancelHandle, TimeStrategy};
use logscope_workspace::{
    NewHypothesis, NewInvestigation, NewItem, NewMarker, NewReportDef, Workspace,
};
use sha2::{Digest, Sha256};

fn write_es_jsonl(path: &Path, records: usize) {
    let mut f = std::io::BufWriter::new(std::fs::File::create(path).unwrap());
    for i in 0..records {
        let level = match i % 5 {
            0 => "ERROR",
            1 => "WARN",
            _ => "INFO",
        };
        writeln!(
            f,
            "{{\"@timestamp\":\"2024-06-01T10:{:02}:{:02}Z\",\"log.level\":\"{level}\",\
             \"message\":\"handler {} finished\",\"service.name\":\"orders\",\"idx\":{i}}}",
            (i / 60) % 60,
            i % 60,
            i,
        )
        .unwrap();
    }
}

fn fg_ctx(job_id: &str) -> (JobContext, JobControl) {
    let (ctx, control, rx) = JobContext::detached(job_id);
    std::mem::forget(rx);
    (ctx, control)
}

fn first_record_ids(ws: &Workspace, engine: &EngineConnection, n: u32) -> Vec<(String, String)> {
    let selection = explorer::resolve_dataset_selection(ws, &[]).unwrap();
    let files = explorer::segment_files_for(ws, &selection).unwrap();
    let analysis = explorer::analyze_query(ws, &selection, "");
    let filter = explorer::compile_for_execution(ws, &selection, &analysis).unwrap();
    let cancel = QueryCancelHandle::new(engine.interrupt_handle());
    let window = logscope_query::resolve_window(&TimeStrategy::All, None);
    let page = query_page(
        engine,
        &files,
        &filter,
        &window,
        &PageRequest {
            cursor: None,
            backward: false,
            limit: n,
        },
        &cancel,
        None,
    )
    .unwrap();
    page.rows
        .into_iter()
        .map(|r| (r.dataset_id, r.record_id))
        .collect()
}

fn sha_hex(bytes: &[u8]) -> String {
    let mut s = String::new();
    for b in Sha256::digest(bytes) {
        use std::fmt::Write;
        let _ = write!(s, "{b:02x}");
    }
    s
}

#[test]
fn full_case_lifecycle_import_to_bundle_reimport() {
    let dir = tempfile::tempdir().unwrap();
    let input = dir.path().join("input.jsonl");
    write_es_jsonl(&input, 240);

    // ---- import through the real job path.
    let mut ws = Workspace::create(&dir.path().join("ws"), "e2e", "0.3.0-test").unwrap();
    let engine = EngineConnection::open_in_memory().unwrap();
    let (ctx, _control) = fg_ctx("job-e2e-import");
    let outcome = run_import(
        &mut ws,
        &engine,
        &ImportRequest::new(vec![input.clone()], builtin::elasticsearch_export(), "es"),
        &ctx,
    )
    .expect("import succeeds");
    assert_eq!(outcome.accepted, 240);

    // ---- investigate: investigation, hypothesis, item, marker.
    let inv = ws
        .meta
        .create_investigation(&NewInvestigation {
            investigation_id: "inv-e2e".into(),
            title: "checkout latency spike".into(),
            description: Some("orders backend errors during deploy".into()),
            severity: Some("sev2".into()),
            owner_text: None,
            tags_json: "[\"deploy\",\"orders\"]".into(),
            incident_started_at: None,
            window_start: None,
            window_end: None,
        })
        .unwrap();

    let hyp = ws
        .meta
        .create_hypothesis(&NewHypothesis {
            hypothesis_id: "hyp-e2e".into(),
            investigation_id: inv.investigation_id.clone(),
            statement: "the 10:00 deploy introduced the failures".into(),
            rationale: Some("errors start at the deploy marker".into()),
        })
        .unwrap();

    ws.meta
        .create_item(&NewItem {
            item_id: "item-e2e".into(),
            investigation_id: inv.investigation_id.clone(),
            kind: "note".into(),
            content: "rollback window is 30 minutes".into(),
            task_status: None,
            question_status: None,
        })
        .unwrap();

    // Marker time goes through the same parser the command layer uses;
    // the original text + zone offset must survive the whole round trip.
    let marker_text = "2026-08-04T12:00:00+02:00";
    let (at_nanos, offset_min) = timeline::parse_marker_time(marker_text).unwrap();
    assert_eq!(at_nanos, 1_785_837_600_000_000_000);
    assert_eq!(offset_min, 120);
    let marker = ws
        .meta
        .create_marker(&NewMarker {
            marker_id: "mark-e2e".into(),
            investigation_id: inv.investigation_id.clone(),
            kind: "deployment".into(),
            label: "orders deploy".into(),
            description: None,
            at_nanos: Some(at_nanos),
            end_nanos: None,
            original_tz_offset_min: Some(offset_min),
            original_time_text: Some(marker_text.into()),
        })
        .unwrap();

    // ---- pin: ten single events + one bounded selection.
    let ids = first_record_ids(&ws, &engine, 10);
    assert_eq!(ids.len(), 10);
    let mut evidence_ids = Vec::new();
    for (i, (dataset_id, record_id)) in ids.iter().enumerate() {
        let row = case::pin_event(
            &ws,
            &engine,
            &case::PinEventRequest {
                common: PinCommon {
                    investigation_id: inv.investigation_id.clone(),
                    title: format!("event {i}"),
                    annotation: Some("seen during triage".into()),
                    relevance: None,
                    group_id: None,
                },
                dataset_id: dataset_id.clone(),
                record_id: record_id.clone(),
                display_fields: vec![],
                include_raw_excerpt: false,
            },
        )
        .expect("pin event");
        evidence_ids.push(row.evidence_id);
    }
    let selection_row = case::pin_selection(
        &ws,
        &engine,
        &case::PinSelectionRequest {
            common: PinCommon {
                investigation_id: inv.investigation_id.clone(),
                title: "first ten as a set".into(),
                annotation: None,
                relevance: None,
                group_id: None,
            },
            record_ids: ids.iter().map(|(_, r)| r.clone()).collect(),
            scope: QueryScope {
                query_text: String::new(),
                dataset_ids: vec![outcome.dataset_id.clone()],
                time_strategy: TimeStrategy::All,
            },
        },
    )
    .expect("pin selection");
    evidence_ids.push(selection_row.evidence_id.clone());

    // Link the first event to the hypothesis and mark it supported —
    // both the link and the state must survive the bundle round trip.
    let hyp_linked = ws
        .meta
        .link_hypothesis_evidence(&hyp.hypothesis_id, hyp.revision, &evidence_ids[0])
        .unwrap();
    ws.meta
        .set_hypothesis_state(&hyp.hypothesis_id, hyp_linked.revision, "supported")
        .unwrap();

    // ---- verify: everything resolves, in ONE batched dataset lookup.
    let (ctx, _control) = fg_ctx("job-e2e-verify");
    let verify = case::verify_evidence(&ws, &engine, &inv.investigation_id, None, &ctx).unwrap();
    assert_eq!(verify.total, 11);
    assert_eq!(verify.dataset_lookups, 1, "no-N+1 verification");
    assert_eq!(verify.states.get("verified"), Some(&11));

    // ---- timeline: dated events + marker, undated selection with reason.
    let tl = timeline::timeline(&ws, &inv.investigation_id).unwrap();
    assert_eq!(tl.dated.len(), 11, "10 dated events + the marker");
    assert_eq!(tl.undated.len(), 1, "the all-time selection is undated");
    assert_eq!(tl.archived_excluded, 0);
    let last = tl.dated.last().unwrap();
    assert_eq!(
        last.id, marker.marker_id,
        "2026 marker sorts after 2024 events"
    );
    assert!(
        tl.undated[0].undated_reason.is_some(),
        "an undated entry states its reason"
    );

    // ---- report: preview IS the artifact bytes, and generation is
    // deterministic across runs.
    let selected: Vec<serde_json::Value> = evidence_ids
        .iter()
        .map(|id| {
            let row = ws.meta.get_evidence(id).unwrap().unwrap();
            serde_json::json!({"id": row.evidence_id, "revision": row.revision})
        })
        .collect();
    let def = ws
        .meta
        .create_report_def(&NewReportDef {
            report_def_id: "rep-e2e".into(),
            investigation_id: inv.investigation_id.clone(),
            title: "checkout latency spike — findings".into(),
            subtitle: Some("e2e".into()),
            sections_json: serde_json::json!([
                {"kind": "summary", "content": "deploy correlated with errors"},
                {"kind": "timeline"},
                {"kind": "evidence"},
            ])
            .to_string(),
            selected_evidence_json: serde_json::to_string(&selected).unwrap(),
            selected_markers_json: serde_json::json!([
                {"id": marker.marker_id, "revision": marker.revision}
            ])
            .to_string(),
            options_json: "{}".into(),
        })
        .unwrap();

    let md_path = dir.path().join("out").join("report.md");
    let preview =
        report::render_preview(&ws, &def.report_def_id, report::ReportFormat::Markdown).unwrap();
    let artifact = report::generate_report(
        &ws,
        &def.report_def_id,
        report::ReportFormat::Markdown,
        &md_path,
    )
    .unwrap();
    let md_bytes = std::fs::read(&md_path).unwrap();
    assert_eq!(preview.as_bytes(), &md_bytes[..], "preview == final bytes");
    assert_eq!(artifact.status, "completed");
    assert_eq!(
        artifact.checksum_sha256.as_deref(),
        Some(sha_hex(&md_bytes).as_str())
    );

    let md2_path = dir.path().join("out").join("report-again.md");
    report::generate_report(
        &ws,
        &def.report_def_id,
        report::ReportFormat::Markdown,
        &md2_path,
    )
    .unwrap();
    assert_eq!(
        md_bytes,
        std::fs::read(&md2_path).unwrap(),
        "generation is byte-deterministic"
    );

    let html_path = dir.path().join("out").join("report.html");
    report::generate_report(
        &ws,
        &def.report_def_id,
        report::ReportFormat::Html,
        &html_path,
    )
    .unwrap();

    // ---- bundle export, including the generated reports.
    let options = bundle::BundleOptions {
        redaction_profile_id: None,
        include_reports: true,
    };
    let bundle_path = dir.path().join("out").join("case.logscope-case");
    let export =
        bundle::export_bundle(&ws, &engine, &inv.investigation_id, &bundle_path, &options).unwrap();
    assert_eq!(export.status, "completed");
    let bundle_bytes = std::fs::read(&bundle_path).unwrap();
    assert_eq!(
        export.checksum_sha256.as_deref(),
        Some(sha_hex(&bundle_bytes).as_str())
    );

    let bundle2_path = dir.path().join("out").join("case-2.logscope-case");
    bundle::export_bundle(&ws, &engine, &inv.investigation_id, &bundle2_path, &options).unwrap();
    assert_eq!(
        bundle_bytes,
        std::fs::read(&bundle2_path).unwrap(),
        "bundle export is byte-deterministic"
    );

    // ---- re-import into a NEW isolated workspace.
    let new_root = dir.path().join("imported-ws");
    let summary = bundle::import_bundle(&bundle_path, &new_root, "imported", "0.3.0-test")
        .expect("bundle imports");
    assert_eq!(summary.investigation_id, inv.investigation_id);
    assert_eq!(summary.evidence, 11);
    assert_eq!(summary.hypotheses, 1);
    assert_eq!(summary.items, 1);
    assert_eq!(summary.markers, 1);
    assert!(
        summary.reports >= 1,
        "generated reports travel with the case"
    );
    assert!(
        summary.data_included,
        "default scope carries the parquet subset"
    );

    let ws2 = Workspace::open(&new_root, "0.3.0-test").unwrap();
    assert!(ws2.recovery.is_clean(), "a fresh import needs no recovery");

    let inv2 = ws2
        .meta
        .get_investigation(&inv.investigation_id)
        .unwrap()
        .unwrap();
    assert_eq!(inv2.title, inv.title);
    assert_eq!(inv2.severity.as_deref(), Some("sev2"));

    assert_eq!(
        ws2.meta
            .list_evidence(&inv.investigation_id, true)
            .unwrap()
            .len(),
        11
    );
    let hyps = ws2.meta.list_hypotheses(&inv.investigation_id).unwrap();
    assert_eq!(hyps.len(), 1);
    assert_eq!(
        hyps[0].state, "supported",
        "hypothesis state survives the round trip"
    );
    assert_eq!(
        ws2.meta
            .linked_evidence_ids(&hyps[0].hypothesis_id)
            .unwrap(),
        vec![evidence_ids[0].clone()],
        "hypothesis links survive the round trip"
    );
    assert_eq!(
        ws2.meta
            .list_items(&inv.investigation_id, true)
            .unwrap()
            .len(),
        1
    );

    let markers2 = ws2.meta.list_markers(&inv.investigation_id, true).unwrap();
    assert_eq!(markers2.len(), 1);
    assert_eq!(markers2[0].at_nanos, Some(at_nanos));
    assert_eq!(markers2[0].original_tz_offset_min, Some(offset_min));
    assert_eq!(markers2[0].original_time_text.as_deref(), Some(marker_text));

    // Report DEFINITIONS do not travel (documented residual): the case
    // ships its generated artifacts as inert files instead, because a
    // regenerated report in the destination could not reach the
    // canonical dataset and would silently differ from what was shared.
    assert_eq!(
        ws2.meta
            .list_report_defs(&inv.investigation_id)
            .unwrap()
            .len(),
        0
    );

    // Import provenance is recorded in the destination.
    let imports = ws2.meta.list_bundle_imports().unwrap();
    assert_eq!(imports.len(), 1);
    assert_eq!(imports[0].bundle_checksum, sha_hex(&bundle_bytes));

    // Bundled reports land as inert files, never opened.
    let inert_dir = new_root.join("imported-reports");
    assert!(inert_dir.exists());
    assert!(
        std::fs::read_dir(&inert_dir).unwrap().count() >= 1,
        "the exported report artifacts are present as files"
    );

    // ---- honesty after re-import: the canonical dataset is NOT
    // registered in the new workspace, so verification must report the
    // unavailable revision — never a fake `verified`.
    let engine2 = EngineConnection::open_in_memory().unwrap();
    let (ctx2, _control2) = fg_ctx("job-e2e-verify-imported");
    let verify2 =
        case::verify_evidence(&ws2, &engine2, &inv.investigation_id, None, &ctx2).unwrap();
    assert_eq!(verify2.total, 11);
    assert_eq!(
        verify2.states.get("verified"),
        None,
        "BLOCKED is never PASS"
    );
    assert_eq!(
        verify2.states.get("dataset_revision_unavailable"),
        Some(&11),
        "every evidence row states the honest resolver outcome"
    );

    // The original workspace reopens clean: the whole flow left no
    // tombstones behind.
    drop(ws);
    let ws_again = Workspace::open(&dir.path().join("ws"), "0.3.0-test").unwrap();
    assert!(ws_again.recovery.is_clean());
}
